package com.rebuilding.muscleatlas.appconfig

/**
 * App configuration values generated by BuildKonfig
 * Access Supabase credentials and other build-time config here
 */
object AppConfig {
    val supabaseUrl: String get() = BuildKonfig.SUPABASE_URL
    val supabaseAnonKey: String get() = BuildKonfig.SUPABASE_ANON_KEY
}
